require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AbcsController do

  # This should return the minimal set of attributes required to create a valid
  # Abc. As you add validations to Abc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AbcsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all abcs as @abcs" do
      abc = Abc.create! valid_attributes
      get :index, {}, valid_session
      assigns(:abcs).should eq([abc])
    end
  end

  describe "GET show" do
    it "assigns the requested abc as @abc" do
      abc = Abc.create! valid_attributes
      get :show, {:id => abc.to_param}, valid_session
      assigns(:abc).should eq(abc)
    end
  end

  describe "GET new" do
    it "assigns a new abc as @abc" do
      get :new, {}, valid_session
      assigns(:abc).should be_a_new(Abc)
    end
  end

  describe "GET edit" do
    it "assigns the requested abc as @abc" do
      abc = Abc.create! valid_attributes
      get :edit, {:id => abc.to_param}, valid_session
      assigns(:abc).should eq(abc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Abc" do
        expect {
          post :create, {:abc => valid_attributes}, valid_session
        }.to change(Abc, :count).by(1)
      end

      it "assigns a newly created abc as @abc" do
        post :create, {:abc => valid_attributes}, valid_session
        assigns(:abc).should be_a(Abc)
        assigns(:abc).should be_persisted
      end

      it "redirects to the created abc" do
        post :create, {:abc => valid_attributes}, valid_session
        response.should redirect_to(Abc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved abc as @abc" do
        # Trigger the behavior that occurs when invalid params are submitted
        Abc.any_instance.stub(:save).and_return(false)
        post :create, {:abc => { "name" => "invalid value" }}, valid_session
        assigns(:abc).should be_a_new(Abc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Abc.any_instance.stub(:save).and_return(false)
        post :create, {:abc => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested abc" do
        abc = Abc.create! valid_attributes
        # Assuming there are no other abcs in the database, this
        # specifies that the Abc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Abc.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => abc.to_param, :abc => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested abc as @abc" do
        abc = Abc.create! valid_attributes
        put :update, {:id => abc.to_param, :abc => valid_attributes}, valid_session
        assigns(:abc).should eq(abc)
      end

      it "redirects to the abc" do
        abc = Abc.create! valid_attributes
        put :update, {:id => abc.to_param, :abc => valid_attributes}, valid_session
        response.should redirect_to(abc)
      end
    end

    describe "with invalid params" do
      it "assigns the abc as @abc" do
        abc = Abc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Abc.any_instance.stub(:save).and_return(false)
        put :update, {:id => abc.to_param, :abc => { "name" => "invalid value" }}, valid_session
        assigns(:abc).should eq(abc)
      end

      it "re-renders the 'edit' template" do
        abc = Abc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Abc.any_instance.stub(:save).and_return(false)
        put :update, {:id => abc.to_param, :abc => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested abc" do
      abc = Abc.create! valid_attributes
      expect {
        delete :destroy, {:id => abc.to_param}, valid_session
      }.to change(Abc, :count).by(-1)
    end

    it "redirects to the abcs list" do
      abc = Abc.create! valid_attributes
      delete :destroy, {:id => abc.to_param}, valid_session
      response.should redirect_to(abcs_url)
    end
  end

end
